<?php
/**
 * 201DataWebhookEventTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sendy Public API
 *
 * In order to get started with Sendy Public API, you will need to first <a href=\"https://app.sendyit.com/auth/sign_up\">register a business account</a>.<br>   Thereafter, <a href=\"https://app.sendyit.com/auth\">login</a> to the Sendy app, create a password and generate a personal access token for API authentication.<br><br>   This guide details interfaces that allow you to integrate your own apps with Sendy's services.<br>
 *
 * The version of the OpenAPI document: de1aa17a-d33f-4aca-9dc5-98822ff83a8f
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * 201DataWebhookEventTest Class Doc Comment
 *
 * @category    Class
 * @description 201DataWebhookEvent
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class 201DataWebhookEventTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "201DataWebhookEvent"
     */
    public function test201DataWebhookEvent()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
