<?php
/**
 * WebhooksApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sendy Public API
 *
 * In order to get started with Sendy Public API, you will need to first <a href=\"https://app.sendyit.com/auth/sign_up\">register a business account</a>.<br>   Thereafter, <a href=\"https://app.sendyit.com/auth\">login</a> to the Sendy app, create a password and generate a personal access token for API authentication.<br><br>   This guide details interfaces that allow you to integrate your own apps with Sendy's services.<br>
 *
 * The version of the OpenAPI document: de1aa17a-d33f-4aca-9dc5-98822ff83a8f
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * WebhooksApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WebhooksApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addawebhook
     *
     * Add a webhook.
     *
     */
    public function testAddawebhook()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for generatepassword
     *
     * Generate password.
     *
     */
    public function testGeneratepassword()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getcancelreasons
     *
     * Get cancel reasons.
     *
     */
    public function testGetcancelreasons()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getsettings
     *
     * Get settings.
     *
     */
    public function testGetsettings()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getvendortypes
     *
     * Get vendor types.
     *
     */
    public function testGetvendortypes()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getwebhookevents
     *
     * Get webhook events.
     *
     */
    public function testGetwebhookevents()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getwebhooks
     *
     * Get webhooks.
     *
     */
    public function testGetwebhooks()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pricerequest
     *
     * Price request.
     *
     */
    public function testPricerequest()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateawebhook
     *
     * Update a webhook.
     *
     */
    public function testUpdateawebhook()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
